# Generated by Django 4.2.5 on 2023-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_add_company_team_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
