# Generated by Django 4.2.5 on 2023-10-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0002_add_company_team_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="org.company",
            ),
        ),
    ]
