# Generated by Django 4.2.5 on 2023-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0003_add_company_team_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birthday",
            field=models.DateField(max_length=20),
        ),
    ]
